### ISSUE TITLE
Need Help to use this Node

### ISSUE THREAD

**Issue by Strippo207** [iceglow/node-red-contrib-volkswagen-we#2]
Hello,

I need help to use this node I have not much experience with Node Red, so If sombody use this Node please be so kind and share a sample flow to set it up, thank you so much.

**Comment by iceglow** [comment]
Hi @Strippo207,
You'll find a [simple-sample.json](https://github.com/iceglow/node-red-contrib-volkswagen-we/blob/master/examples/simple-sample.json) under the [examples](https://github.com/iceglow/node-red-contrib-volkswagen-we/blob/master/examples/) folder. You can [import](https://nodered.org/docs/user-guide/editor/workspace/import-export) that into your flow, configure the "we-connect-login"-node and it should work.
