### ISSUE TITLE
login data can be used for two http request only

### ISSUE THREAD

**Issue by Langer75** [iceglow/node-red-contrib-volkswagen-we#3]
Hi, the node is working perfect. Thanks for your work. But unfortunately the login data can be used only for two http requests. For further requests you have to login again via your node. I logged the networktraffic of the "we portal" in Chrome browser. As I understand it the traffic is based on always the same login data. I also tried the option "Enable connection keep-alive" in the http request node. But nothing changed. Does anybody have an idea how it works without login in again after two requests?

Thanks and regards
Andreas

**Comment by iceglow** [comment]
Hi @Langer75,
I use the login data for several requests, periodically checking status etc.
In my setup I use [node-red-contrib-cache](https://flows.nodered.org/node/node-red-contrib-cache) to cache the login result.
In the setup I have, I'm firing ~3-4 requests/minute. How far in between are your requests?

**Comment by Langer75** [comment]
Hi iceglow
I use flow.set for caching the login data. To my understanding this should work as well for caching the login result. At least once it works. For the first http request login result comes directly from your node. The second one is working with flow.get. Does flow.get only work once?
I will make a try with node-red-contrib-cache. I will come back with feedback.
Thanks
Langer75

**Comment by Langer75** [comment]
Hi iceglow
I tried the node-red-contrib-cache and it works. I don't Know why flow.set and flow.get does not work more than once. Anyway, thank you for your hint. May be this hint is also useful for other users.
